[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<Anchor.ino> +<anchor.cpp> +<uwb-node.cpp> +<scheduler.cpp>
lib_deps = https://github.com/Makerfabs/Makerfabs-ESP32-UWB-DW3000.git
