[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<main.cpp> +<anchor.cpp> +<uwb-node.cpp> +<scheduler.cpp>
build_unflags = -std=gnu++11
build_flags = -std=gnu++14
monitor_speed = 115200
lib_deps = https://github.com/Makerfabs/Makerfabs-ESP32-UWB-DW3000.git
